apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-auth-keb
  namespace: kcp-system
spec:
  jwtRules:
  {{- if .Values.oidc.issuers }}
  {{- range $i, $p := .Values.oidc.issuers }}
    - issuer: {{ tpl $p $ }}
      jwksUri: {{ tpl (print $p "/oauth2/certs") $ }}
  {{- end }}
  {{- else }}
    - issuer: {{ tpl .Values.oidc.issuer $ }}
      jwksUri: {{ tpl (print .Values.oidc.issuer "/oauth2/certs") $ }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kyma-env-broker.name" . }}
      app.kubernetes.io/instance: {{ .Values.namePrefix }}
